package cn.sz.hcq.pojo;

// Generated 2017-11-9 19:41:47 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ZxAdmin generated by hbm2java
 */
@Entity
@Table(name = "zx_admin", catalog = "zouxiu")
public class Admin implements java.io.Serializable {

	private Integer aid;
	private String loginName;
	private String loginPwd;
	private String nickName;
	private String realName;
	private Set<Log> logs = new HashSet<Log>(0);

	public Admin() {
	}

	public Admin(String loginName, String loginPwd, String nickName,
			String realName) {
		this.loginName = loginName;
		this.loginPwd = loginPwd;
		this.nickName = nickName;
		this.realName = realName;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "aid", unique = true, nullable = false)
	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	@Column(name = "loginName", length = 30)
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	@Column(name = "loginPwd", length = 30)
	public String getLoginPwd() {
		return this.loginPwd;
	}

	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd;
	}

	@Column(name = "nickName", length = 30)
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "realName", length = 30)
	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admin")
	public Set<Log> getLogs() {
		return this.logs;
	}

	public void setLogs(Set<Log> logs) {
		this.logs = logs;
	}

}
