package cn.sz.hcq.pojo;

// Generated 2017-11-9 19:41:47 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ZxLog generated by hbm2java
 */
@Entity
@Table(name = "zx_log", catalog = "zouxiu")
public class Log implements java.io.Serializable {

	private Integer lid;
	private Admin admin;
	private String editProject;
	private String initialValue;
	private String endValue;
	private String operationRecords;
	private Date operationTime;
	private String operationIp;

	public Log() {
	}

	public Log(Admin admin) {
		this.admin = admin;
	}

	public Log(Admin admin, String editProject, String initialValue,
			String endValue, String operationRecords, Date operationTime,
			String operationIp) {
		this.admin = admin;
		this.editProject = editProject;
		this.initialValue = initialValue;
		this.endValue = endValue;
		this.operationRecords = operationRecords;
		this.operationTime = operationTime;
		this.operationIp = operationIp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "lid", unique = true, nullable = false)
	public Integer getLid() {
		return this.lid;
	}

	public void setLid(Integer lid) {
		this.lid = lid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aid", nullable = false)
	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	@Column(name = "editProject", length = 30)
	public String getEditProject() {
		return this.editProject;
	}

	public void setEditProject(String editProject) {
		this.editProject = editProject;
	}

	@Column(name = "initialValue", length = 20)
	public String getInitialValue() {
		return this.initialValue;
	}

	public void setInitialValue(String initialValue) {
		this.initialValue = initialValue;
	}

	@Column(name = "endValue", length = 20)
	public String getEndValue() {
		return this.endValue;
	}

	public void setEndValue(String endValue) {
		this.endValue = endValue;
	}

	@Column(name = "operationRecords", length = 20)
	public String getOperationRecords() {
		return this.operationRecords;
	}

	public void setOperationRecords(String operationRecords) {
		this.operationRecords = operationRecords;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "operationTime", length = 0)
	public Date getOperationTime() {
		return this.operationTime;
	}

	public void setOperationTime(Date operationTime) {
		this.operationTime = operationTime;
	}

	@Column(name = "operationIP", length = 30)
	public String getOperationIp() {
		return this.operationIp;
	}

	public void setOperationIp(String operationIp) {
		this.operationIp = operationIp;
	}

}
