package cn.sz.hcq.pojo;

// Generated 2017-11-10 15:16:25 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ZxProvince generated by hbm2java
 */
@Entity
@Table(name = "zx_province", catalog = "zouxiu")
public class Province implements java.io.Serializable {

	private Integer id;
	private String provinceId;
	private String province;

	public Province() {
	}

	public Province(String provinceId, String province) {
		this.provinceId = provinceId;
		this.province = province;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "provinceID", length = 6)
	public String getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(String provinceId) {
		this.provinceId = provinceId;
	}

	@Column(name = "province", length = 40)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

}
