package cn.sz.hcq.pojo;

// Generated 2017-11-9 19:41:47 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ZxUser generated by hbm2java
 */
@Entity
@Table(name = "zx_user", catalog = "zouxiu")
public class User implements java.io.Serializable {

	private Integer uid;
	private String loginName;
	private String loginPwd;
	private String realName;
	private String phone;
	private String email;
	private Date createTime;
	private String fixphone;
	private Integer syntheticGrade;
	private String sourcePattern;
	private String sourceChannel;
	private Integer sourceChannelGrade;
	private Integer state;
	private String address;
	private String gender;
	private Date birthday;
	private String monthlyIncome;
	private String provinces;
	private String cities;
	private String area;
	private String status;
	private String education;
	private Integer logins;
	private Integer onlineTime;
	private Integer totalAmountPurchase;
	private Long totalMoneyPurchase;
	private Integer comprehensiveIntegral;
	private Integer channelIntegral;
	private Integer activate;
	private Integer aid;
	private String aname;

	public User() {
	}

	public User(String loginName, String loginPwd, String realName,
			String phone, String email, Date createTime, String fixphone,
			Integer syntheticGrade, String sourcePattern, String sourceChannel,
			Integer sourceChannelGrade, Integer state, String address,
			String gender, Date birthday, String monthlyIncome,
			String provinces, String cities, String area, String status,
			String education, Integer logins, Integer onlineTime,
			Integer totalAmountPurchase, Long totalMoneyPurchase,
			Integer comprehensiveIntegral, Integer channelIntegral,
			Integer activate, Integer aid, String aname) {
		this.loginName = loginName;
		this.loginPwd = loginPwd;
		this.realName = realName;
		this.phone = phone;
		this.email = email;
		this.createTime = createTime;
		this.fixphone = fixphone;
		this.syntheticGrade = syntheticGrade;
		this.sourcePattern = sourcePattern;
		this.sourceChannel = sourceChannel;
		this.sourceChannelGrade = sourceChannelGrade;
		this.state = state;
		this.address = address;
		this.gender = gender;
		this.birthday = birthday;
		this.monthlyIncome = monthlyIncome;
		this.provinces = provinces;
		this.cities = cities;
		this.area = area;
		this.status = status;
		this.education = education;
		this.logins = logins;
		this.onlineTime = onlineTime;
		this.totalAmountPurchase = totalAmountPurchase;
		this.totalMoneyPurchase = totalMoneyPurchase;
		this.comprehensiveIntegral = comprehensiveIntegral;
		this.channelIntegral = channelIntegral;
		this.activate = activate;
		this.aid = aid;
		this.aname = aname;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "uid", unique = true, nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "loginName", length = 30)
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	@Column(name = "loginPwd", length = 30)
	public String getLoginPwd() {
		return this.loginPwd;
	}

	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd;
	}

	@Column(name = "realName", length = 30)
	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	@Column(name = "phone", length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 0)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "fixphone", length = 100)
	public String getFixphone() {
		return this.fixphone;
	}

	public void setFixphone(String fixphone) {
		this.fixphone = fixphone;
	}

	@Column(name = "syntheticGrade")
	public Integer getSyntheticGrade() {
		return this.syntheticGrade;
	}

	public void setSyntheticGrade(Integer syntheticGrade) {
		this.syntheticGrade = syntheticGrade;
	}

	@Column(name = "sourcePattern", length = 30)
	public String getSourcePattern() {
		return this.sourcePattern;
	}

	public void setSourcePattern(String sourcePattern) {
		this.sourcePattern = sourcePattern;
	}

	@Column(name = "sourceChannel", length = 20)
	public String getSourceChannel() {
		return this.sourceChannel;
	}

	public void setSourceChannel(String sourceChannel) {
		this.sourceChannel = sourceChannel;
	}

	@Column(name = "sourceChannelGrade")
	public Integer getSourceChannelGrade() {
		return this.sourceChannelGrade;
	}

	public void setSourceChannelGrade(Integer sourceChannelGrade) {
		this.sourceChannelGrade = sourceChannelGrade;
	}

	@Column(name = "state")
	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	@Column(name = "address", length = 60)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "Gender", length = 3)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "birthday", length = 0)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "monthlyIncome", length = 20)
	public String getMonthlyIncome() {
		return this.monthlyIncome;
	}

	public void setMonthlyIncome(String monthlyIncome) {
		this.monthlyIncome = monthlyIncome;
	}

	@Column(name = "Provinces", length = 20)
	public String getProvinces() {
		return this.provinces;
	}

	public void setProvinces(String provinces) {
		this.provinces = provinces;
	}

	@Column(name = "cities", length = 20)
	public String getCities() {
		return this.cities;
	}

	public void setCities(String cities) {
		this.cities = cities;
	}

	@Column(name = "area", length = 30)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "education", length = 20)
	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	@Column(name = "Logins")
	public Integer getLogins() {
		return this.logins;
	}

	public void setLogins(Integer logins) {
		this.logins = logins;
	}

	@Column(name = "onlineTime")
	public Integer getOnlineTime() {
		return this.onlineTime;
	}

	public void setOnlineTime(Integer onlineTime) {
		this.onlineTime = onlineTime;
	}

	@Column(name = "totalAmountPurchase")
	public Integer getTotalAmountPurchase() {
		return this.totalAmountPurchase;
	}

	public void setTotalAmountPurchase(Integer totalAmountPurchase) {
		this.totalAmountPurchase = totalAmountPurchase;
	}

	@Column(name = "totalMoneyPurchase", precision = 10, scale = 0)
	public Long getTotalMoneyPurchase() {
		return this.totalMoneyPurchase;
	}

	public void setTotalMoneyPurchase(Long totalMoneyPurchase) {
		this.totalMoneyPurchase = totalMoneyPurchase;
	}

	@Column(name = "comprehensiveIntegral")
	public Integer getComprehensiveIntegral() {
		return this.comprehensiveIntegral;
	}

	public void setComprehensiveIntegral(Integer comprehensiveIntegral) {
		this.comprehensiveIntegral = comprehensiveIntegral;
	}

	@Column(name = "channelIntegral")
	public Integer getChannelIntegral() {
		return this.channelIntegral;
	}

	public void setChannelIntegral(Integer channelIntegral) {
		this.channelIntegral = channelIntegral;
	}

	@Column(name = "activate")
	public Integer getActivate() {
		return this.activate;
	}

	public void setActivate(Integer activate) {
		this.activate = activate;
	}

	@Column(name = "aid")
	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	@Column(name = "aname", length = 30)
	public String getAname() {
		return this.aname;
	}

	public void setAname(String aname) {
		this.aname = aname;
	}

}
